### ISSUE TITLE
Practical exercise for Church encoding 

### ISSUE THREAD

**Issue by yaitskov** [graninas/Functional-Design-and-Architecture#4]
Hi,

I wanted to improve error reporting in beam library, through a runtime pluggable raw row logger, and realized that the library is using Church monad. 

The library is popular meanwhile Church monad is not, so implementing following feature might be a good exercise for the book.

https://github.com/haskell-beam/beam/issues/638

**Comment by graninas** [comment]
Hi, thank you for your comment!

I didn't get what exactly feature you're referencing to. The code you're presenting is not familiar to me

**Comment by yaitskov** [comment]
Beam library, in case of row conversion error, doesn't log raw row or at least a row primary key, only column number. If query is select all it is hard to guess what went wrong (needle in a haystack), because developer has to fix bug without a sample reproducing the bug. So he has to spend extra time for adding extra logging to beam, rebuilding it. All this takes time. For production such silence might be good, but not all tables are equally sensitive. For development is absolutely a plus to have such feature out of the box. So logging row data must be adjustable in runtime => function doing that must be a part of monad context. 

I will write an update once / if I succeed in this endeavor.

**Comment by graninas** [comment]
@yaitskov Good luck! It's true that it has some flaws in terms of debugging and logging. 

The beam library is not the best one for sure, and I'd rather argue to avoid it if possible though. I'm kind of ambivalent about having it in my book, but I don't plan to replace it for now - no need and no time
