### ISSUE TITLE
GHC version issue in macOS m2

### ISSUE THREAD

**Issue by kindofdev** [graninas/Functional-Design-and-Architecture#5]
Hello, I'm struggling to build the projects on a macOS laptop with a m2 chip.
For instance when I run `stack build` on "Functional-Design-and-Architecture/Manning-Publications/BookSamples/CH03/Section3p3" I get the following error. 

```console
No setup information found for ghc-8.8.4 on your platform. This probably means a GHC binary distribution has not yet been added for OS key macosx-aarch64. Supported versions: ghc-8.10.5,
       ghc-8.10.6, ghc-8.10.7, ghc-9.0.2, ghc-9.2.1, ghc-9.2.2, ghc-9.2.3, ghc-9.2.4, ghc-9.2.5, ghc-9.2.6, ghc-9.2.7, ghc-9.2.8, ghc-9.4.1, ghc-9.4.2, ghc-9.4.3, ghc-9.4.4, ghc-9.4.5, ghc-9.4.6,
       ghc-9.4.7, ghc-9.4.8, ghc-9.6.1, ghc-9.6.2, ghc-9.6.3, ghc-9.6.4, ghc-9.6.5, ghc-9.6.6, ghc-9.8.1, ghc-9.8.2 and ghc-9.10.1.
```

Notice that I've tried to replace the **resolver** in **stack.yaml** with the GHC versions suggested but I get other errors related to raven-haskell. 

Thank you!

**Comment by graninas** [comment]
@kindofdev I just discovered your comment. Thank you for asking!

Unfortunately, I have little knowledge of how Haskell is supported on macOS and don't have any Apple production to test it. If this is a huge issue to you, as a temporary solution, comment out haskell-raven dependency and `BookSamples/CH10/Section10p1` in your stack.yaml file. All other projects don't require it.

If you find a way to build with raven-haskell, plz inform me about the solution.

Also, I'll consider updating the code to remove the real dependency and only make it a mock implementation.
